# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jan  3 14:02:10 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(390, 315)
        MainWindow.setMinimumSize(QtCore.QSize(390, 315))
        MainWindow.setMaximumSize(QtCore.QSize(390, 315))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.btnFileChoose = QtGui.QPushButton(self.centralWidget)
        self.btnFileChoose.setGeometry(QtCore.QRect(30, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.btnFileChoose.setFont(font)
        self.btnFileChoose.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnFileChoose.setObjectName(_fromUtf8("btnFileChoose"))
        self.lbFilePath = QtGui.QLabel(self.centralWidget)
        self.lbFilePath.setGeometry(QtCore.QRect(130, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbFilePath.setFont(font)
        self.lbFilePath.setObjectName(_fromUtf8("lbFilePath"))
        self.btnStart = QtGui.QPushButton(self.centralWidget)
        self.btnStart.setGeometry(QtCore.QRect(140, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(16)
        font.setItalic(False)
        self.btnStart.setFont(font)
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnStart.setAutoFillBackground(True)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.btnOutputPath = QtGui.QPushButton(self.centralWidget)
        self.btnOutputPath.setGeometry(QtCore.QRect(30, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setItalic(False)
        self.btnOutputPath.setFont(font)
        self.btnOutputPath.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnOutputPath.setAutoFillBackground(True)
        self.btnOutputPath.setObjectName(_fromUtf8("btnOutputPath"))
        self.lbOutputPath = QtGui.QLabel(self.centralWidget)
        self.lbOutputPath.setGeometry(QtCore.QRect(130, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbOutputPath.setFont(font)
        self.lbOutputPath.setObjectName(_fromUtf8("lbOutputPath"))
        self.cbWidth = QtGui.QCheckBox(self.centralWidget)
        self.cbWidth.setGeometry(QtCore.QRect(20, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbWidth.setFont(font)
        self.cbWidth.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cbWidth.setChecked(True)
        self.cbWidth.setObjectName(_fromUtf8("cbWidth"))
        self.cbHeight = QtGui.QCheckBox(self.centralWidget)
        self.cbHeight.setGeometry(QtCore.QRect(20, 160, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cbHeight.setFont(font)
        self.cbHeight.setChecked(True)
        self.cbHeight.setObjectName(_fromUtf8("cbHeight"))
        self.cbRate = QtGui.QCheckBox(self.centralWidget)
        self.cbRate.setGeometry(QtCore.QRect(20, 200, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbRate.setFont(font)
        self.cbRate.setChecked(True)
        self.cbRate.setObjectName(_fromUtf8("cbRate"))
        self.grpWidth = QtGui.QGroupBox(self.centralWidget)
        self.grpWidth.setEnabled(True)
        self.grpWidth.setGeometry(QtCore.QRect(90, 110, 291, 41))
        self.grpWidth.setTitle(_fromUtf8(""))
        self.grpWidth.setFlat(True)
        self.grpWidth.setCheckable(False)
        self.grpWidth.setObjectName(_fromUtf8("grpWidth"))
        self.label = QtGui.QLabel(self.grpWidth)
        self.label.setGeometry(QtCore.QRect(70, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.sbWidth = QtGui.QSpinBox(self.grpWidth)
        self.sbWidth.setGeometry(QtCore.QRect(0, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sbWidth.setFont(font)
        self.sbWidth.setMaximum(20000)
        self.sbWidth.setProperty("value", 1440)
        self.sbWidth.setObjectName(_fromUtf8("sbWidth"))
        self.groupBox = QtGui.QGroupBox(self.grpWidth)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(110, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbWidthGt = QtGui.QRadioButton(self.groupBox)
        self.rbWidthGt.setGeometry(QtCore.QRect(0, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbWidthGt.setFont(font)
        self.rbWidthGt.setChecked(True)
        self.rbWidthGt.setObjectName(_fromUtf8("rbWidthGt"))
        self.rbWidthLt = QtGui.QRadioButton(self.groupBox)
        self.rbWidthLt.setGeometry(QtCore.QRect(60, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbWidthLt.setFont(font)
        self.rbWidthLt.setObjectName(_fromUtf8("rbWidthLt"))
        self.rbWidthEq = QtGui.QRadioButton(self.groupBox)
        self.rbWidthEq.setGeometry(QtCore.QRect(120, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbWidthEq.setFont(font)
        self.rbWidthEq.setObjectName(_fromUtf8("rbWidthEq"))
        self.grpHeight = QtGui.QGroupBox(self.centralWidget)
        self.grpHeight.setEnabled(True)
        self.grpHeight.setGeometry(QtCore.QRect(90, 150, 291, 41))
        self.grpHeight.setTitle(_fromUtf8(""))
        self.grpHeight.setFlat(True)
        self.grpHeight.setCheckable(False)
        self.grpHeight.setObjectName(_fromUtf8("grpHeight"))
        self.label_2 = QtGui.QLabel(self.grpHeight)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.sbHeight = QtGui.QSpinBox(self.grpHeight)
        self.sbHeight.setGeometry(QtCore.QRect(0, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sbHeight.setFont(font)
        self.sbHeight.setMaximum(20000)
        self.sbHeight.setProperty("value", 900)
        self.sbHeight.setObjectName(_fromUtf8("sbHeight"))
        self.groupBox_2 = QtGui.QGroupBox(self.grpHeight)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(110, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.rbHeightGt = QtGui.QRadioButton(self.groupBox_2)
        self.rbHeightGt.setGeometry(QtCore.QRect(0, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbHeightGt.setFont(font)
        self.rbHeightGt.setChecked(True)
        self.rbHeightGt.setObjectName(_fromUtf8("rbHeightGt"))
        self.rbHeightLt = QtGui.QRadioButton(self.groupBox_2)
        self.rbHeightLt.setGeometry(QtCore.QRect(60, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbHeightLt.setFont(font)
        self.rbHeightLt.setObjectName(_fromUtf8("rbHeightLt"))
        self.rbHeightEq = QtGui.QRadioButton(self.groupBox_2)
        self.rbHeightEq.setGeometry(QtCore.QRect(120, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbHeightEq.setFont(font)
        self.rbHeightEq.setObjectName(_fromUtf8("rbHeightEq"))
        self.grpRate = QtGui.QGroupBox(self.centralWidget)
        self.grpRate.setEnabled(True)
        self.grpRate.setGeometry(QtCore.QRect(90, 200, 291, 41))
        self.grpRate.setTitle(_fromUtf8(""))
        self.grpRate.setFlat(True)
        self.grpRate.setCheckable(False)
        self.grpRate.setObjectName(_fromUtf8("grpRate"))
        self.groupBox_6 = QtGui.QGroupBox(self.grpRate)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setGeometry(QtCore.QRect(198, 0, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.sbRateValue = QtGui.QDoubleSpinBox(self.grpRate)
        self.sbRateValue.setGeometry(QtCore.QRect(170, 0, 62, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sbRateValue.setFont(font)
        self.sbRateValue.setMaximum(1.0)
        self.sbRateValue.setSingleStep(0.01)
        self.sbRateValue.setProperty("value", 0.1)
        self.sbRateValue.setObjectName(_fromUtf8("sbRateValue"))
        self.sbRateWidth = QtGui.QSpinBox(self.grpRate)
        self.sbRateWidth.setGeometry(QtCore.QRect(0, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sbRateWidth.setFont(font)
        self.sbRateWidth.setMaximum(20000)
        self.sbRateWidth.setProperty("value", 1440)
        self.sbRateWidth.setObjectName(_fromUtf8("sbRateWidth"))
        self.label_3 = QtGui.QLabel(self.grpRate)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(70, 0, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_7 = QtGui.QLabel(self.grpRate)
        self.label_7.setGeometry(QtCore.QRect(230, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(False)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sbRateHeight = QtGui.QSpinBox(self.grpRate)
        self.sbRateHeight.setGeometry(QtCore.QRect(100, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sbRateHeight.setFont(font)
        self.sbRateHeight.setMaximum(20000)
        self.sbRateHeight.setProperty("value", 900)
        self.sbRateHeight.setObjectName(_fromUtf8("sbRateHeight"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "imageFilter by 封印的猫", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFileChoose.setText(QtGui.QApplication.translate("MainWindow", "选择文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.lbFilePath.setText(QtGui.QApplication.translate("MainWindow", "未选择筛选目录", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStart.setText(QtGui.QApplication.translate("MainWindow", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutputPath.setText(QtGui.QApplication.translate("MainWindow", "输出文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.lbOutputPath.setText(QtGui.QApplication.translate("MainWindow", "未选择输出目录", None, QtGui.QApplication.UnicodeUTF8))
        self.cbWidth.setText(QtGui.QApplication.translate("MainWindow", " 宽度：", None, QtGui.QApplication.UnicodeUTF8))
        self.cbHeight.setText(QtGui.QApplication.translate("MainWindow", " 高度：", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRate.setText(QtGui.QApplication.translate("MainWindow", " 比例：", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "模式", None, QtGui.QApplication.UnicodeUTF8))
        self.rbWidthGt.setText(QtGui.QApplication.translate("MainWindow", "大于", None, QtGui.QApplication.UnicodeUTF8))
        self.rbWidthLt.setText(QtGui.QApplication.translate("MainWindow", "小于", None, QtGui.QApplication.UnicodeUTF8))
        self.rbWidthEq.setText(QtGui.QApplication.translate("MainWindow", "等于", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "模式", None, QtGui.QApplication.UnicodeUTF8))
        self.rbHeightGt.setText(QtGui.QApplication.translate("MainWindow", "大于", None, QtGui.QApplication.UnicodeUTF8))
        self.rbHeightLt.setText(QtGui.QApplication.translate("MainWindow", "小于", None, QtGui.QApplication.UnicodeUTF8))
        self.rbHeightEq.setText(QtGui.QApplication.translate("MainWindow", "等于", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#088341;\">：</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#409d39;\">浮动值</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

